# Generated by Django 5.1.4 on 2024-12-11 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstitutionDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("taalim", models.CharField(max_length=100)),
                ("moh_name", models.CharField(max_length=200)),
                ("moh_phone", models.CharField(max_length=50)),
                ("safir_name", models.CharField(max_length=200)),
                ("safir_phone", models.CharField(max_length=50)),
                (
                    "safir_aadhar",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("res_students", models.IntegerField(default=0)),
                ("total_students", models.IntegerField(default=0)),
                ("total_teachers", models.IntegerField(default=0)),
                ("donation_day", models.IntegerField(default=0)),
                ("serial_no", models.IntegerField(default=0)),
                (
                    "halka_code",
                    models.CharField(
                        choices=[("A", "A"), ("B", "B"), ("V", "V")], max_length=1
                    ),
                ),
                (
                    "ijazat_status",
                    models.CharField(choices=[("Y", "Yes"), ("N", "No")], max_length=1),
                ),
                ("comments", models.TextField(blank=True, null=True)),
                (
                    "safir_photo",
                    models.FileField(blank=True, null=True, upload_to="media/photos/"),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.institution",
                    ),
                ),
                (
                    "next_donation_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="next_donation_year",
                        to="main.year",
                    ),
                ),
                (
                    "year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="current_year",
                        to="main.year",
                    ),
                ),
            ],
        ),
    ]
