# Generated by Django 5.1.4 on 2024-12-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_alter_institution_created_alter_institution_state_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institution",
            name="state",
            field=models.IntegerField(),
        ),
    ]
