# Generated by Django 5.1.4 on 2024-12-13 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_alter_institution_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institutiondetails",
            name="institution",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="institutiondetails",
            name="next_donation_year",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="institutiondetails",
            name="year",
            field=models.IntegerField(),
        ),
    ]
