# Generated by Django 5.1.4 on 2024-12-13 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_alter_institutiondetails_institution_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institutiondetails",
            name="created",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="institutiondetails",
            name="updated",
            field=models.DateTimeField(),
        ),
    ]
