# Generated by Django 5.1.4 on 2024-12-13 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_alter_institutiondetails_created_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institution",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="institution",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="institutiondetails",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="institutiondetails",
            name="institution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.institution"
            ),
        ),
        migrations.AlterField(
            model_name="institutiondetails",
            name="next_donation_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="next_donation_year",
                to="main.year",
            ),
        ),
        migrations.AlterField(
            model_name="institutiondetails",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="institutiondetails",
            name="year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="current_year",
                to="main.year",
            ),
        ),
    ]
