# Generated by Django 5.1.4 on 2024-12-21 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_alter_institution_created_alter_institution_updated_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institutiondetails",
            name="institution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="idetail",
                to="main.institution",
            ),
        ),
        migrations.AlterField(
            model_name="institutiondetails",
            name="year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="iyear",
                to="main.year",
            ),
        ),
    ]
