# Generated by Django 5.1.4 on 2024-12-27 03:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_alter_institutiondetails_institution_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institutiondetails",
            name="donation_day",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(4),
                    django.core.validators.MaxValueValidator(24),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="institutiondetails",
            name="next_donation_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="next_donation_year",
                to="main.year",
                validators=[django.core.validators.MinValueValidator(2024)],
            ),
        ),
    ]
