# Generated by Django 5.1.4 on 2024-12-30 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_alter_institutiondetails_donation_day_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institutiondetails",
            name="next_donation_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="next_donation_year",
                to="main.year",
            ),
        ),
    ]
