# Generated by Django 5.1.4 on 2024-12-30 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_alter_institutiondetails_next_donation_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institutiondetails",
            name="donation_day",
            field=models.IntegerField(default=0),
        ),
    ]
